language: python
python:
  - '3.9'

before_script:
  pip install -r requirements.txt
  ls -la

branches:
  only:
    - staging

env: DJANGO_SETTINGS_MODULE="purbeurre.purbeurre.settings.travis"

services:
  - postresql

script:
  - python manage.py test