# Generated by Django 3.2 on 2021-05-18 14:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('translated_name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('barcode', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('url', models.URLField(unique=True)),
                ('picture_url', models.URLField(unique=True)),
                ('nutriscore', models.CharField(max_length=3)),
                ('stores', models.CharField(blank=True, max_length=1000)),
                ('sugars', models.FloatField(blank=True, default=-1)),
                ('fats', models.FloatField(blank=True, default=-1)),
                ('proteins', models.FloatField(blank=True, default=-1)),
                ('kcals', models.FloatField(blank=True, default=-1)),
                ('salt', models.FloatField(blank=True, default=-1)),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('product_categories', models.ManyToManyField(blank=True, related_name='product_categories', to='research.Category')),
            ],
        ),
    ]
